# See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks
repos:
   -   repo: git@github.com:SergeyErshov/b5-practise.git
       rev: v1.0.1

         hooks:
             - id: terraform_fmt
             - id: terraform_validate
             - id: terraform_docs
             - id: terraform_tflint
#
